### ISSUE TITLE
Installation page is inaccessible

### ISSUE THREAD

**Issue by kyukhin** [intel-hpdd/lustre-connector-for-hadoop#1]
Link mentioned in Readme.md [1] cannot be accessed w/o some special account.

[1] - https://wiki.hpdd.intel.com/display/SR/Installation+of+HAL+on+Apache+Hadoop

**Comment by liy106** [comment]
Thanks for reminding me. I will export it to a txt file here soon.

**Comment by liy106** [comment]
The patch is merged (commit fc52f9d704ffe3a3b308828a3976defac1cb3a66).
