### ISSUE TITLE
java.lang.SecurityException 

### ISSUE THREAD

**Issue by trevoryu** [intel-hpdd/lustre-connector-for-hadoop#2]
When I ran this command : hadoop fs -mkdir /test1/test2. 
I had the java exception : class "org.apache.hadoop.fs.LustreFileSystem"'s signer information does not match signer information of other classes in the same package.
Do you know what problem is.

**Comment by liy106** [comment]
Sorry for my late reply. There are typos in file src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem. I should use "#" instead of "//" for comments.

**Comment by liy106** [comment]
The patch is merged (commit 6af584db0cf491514f591c4a443812e12584cdcb).
